name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install --upgrade pip
          pip install buildozer

      - name: Install dependencies
        run: |
          buildozer init

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: overcurrent-protection-apk
          path: bin/*.apk
